<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LgasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        // Fetch the state IDs for the states
        $states = DB::table('states')->pluck('id', 'name')->toArray();

        $lgas = [
            // Anambra State
            ['state_id' => $states['Anambra'], 'name' => 'Aguata'],
            ['state_id' => $states['Anambra'], 'name' => 'Anambra East'],
            ['state_id' => $states['Anambra'], 'name' => 'Anambra West'],
            ['state_id' => $states['Anambra'], 'name' => 'Anaocha'],
            ['state_id' => $states['Anambra'], 'name' => 'Awka North'],
            ['state_id' => $states['Anambra'], 'name' => 'Awka South'],
            ['state_id' => $states['Anambra'], 'name' => 'Ayamelum'],
            ['state_id' => $states['Anambra'], 'name' => 'Dunukofia'],
            ['state_id' => $states['Anambra'], 'name' => 'Ekwusigo'],
            ['state_id' => $states['Anambra'], 'name' => 'Idemili North'],
            ['state_id' => $states['Anambra'], 'name' => 'Idemili South'],
            ['state_id' => $states['Anambra'], 'name' => 'Ihiala'],
            ['state_id' => $states['Anambra'], 'name' => 'Njikoka'],
            ['state_id' => $states['Anambra'], 'name' => 'Nnewi North'],
            ['state_id' => $states['Anambra'], 'name' => 'Nnewi South'],
            ['state_id' => $states['Anambra'], 'name' => 'Ogbaru'],
            ['state_id' => $states['Anambra'], 'name' => 'Onitsha North'],
            ['state_id' => $states['Anambra'], 'name' => 'Onitsha South'],
            ['state_id' => $states['Anambra'], 'name' => 'Orumba North'],
            ['state_id' => $states['Anambra'], 'name' => 'Orumba South'],
            ['state_id' => $states['Anambra'], 'name' => 'Oyi'],

            // Bauchi State
            ['state_id' => $states['Bauchi'], 'name' => 'Alkaleri'],
            ['state_id' => $states['Bauchi'], 'name' => 'Bauchi'],
            ['state_id' => $states['Bauchi'], 'name' => 'Bogoro'],
            ['state_id' => $states['Bauchi'], 'name' => 'Damban'],
            ['state_id' => $states['Bauchi'], 'name' => 'Darazo'],
            ['state_id' => $states['Bauchi'], 'name' => 'Dass'],
            ['state_id' => $states['Bauchi'], 'name' => 'Gamawa'],
            ['state_id' => $states['Bauchi'], 'name' => 'Ganjuwa'],
            ['state_id' => $states['Bauchi'], 'name' => 'Giade'],
            ['state_id' => $states['Bauchi'], 'name' => 'Itas/Gadau'],
            ['state_id' => $states['Bauchi'], 'name' => 'Jama\'are'],
            ['state_id' => $states['Bauchi'], 'name' => 'Katagum'],
            ['state_id' => $states['Bauchi'], 'name' => 'Kirfi'],
            ['state_id' => $states['Bauchi'], 'name' => 'Misau'],
            ['state_id' => $states['Bauchi'], 'name' => 'Ningi'],
            ['state_id' => $states['Bauchi'], 'name' => 'Shira'],
            ['state_id' => $states['Bauchi'], 'name' => 'Tafawa Balewa'],
            ['state_id' => $states['Bauchi'], 'name' => 'Toro'],
            ['state_id' => $states['Bauchi'], 'name' => 'Warji'],
            ['state_id' => $states['Bauchi'], 'name' => 'Zaki'],

            // Bayelsa State
            ['state_id' => $states['Bayelsa'], 'name' => 'Brass'],
            ['state_id' => $states['Bayelsa'], 'name' => 'Ekeremor'],
            ['state_id' => $states['Bayelsa'], 'name' => 'Kolokuma/Opokuma'],
            ['state_id' => $states['Bayelsa'], 'name' => 'Nembe'],
            ['state_id' => $states['Bayelsa'], 'name' => 'Ogbia'],
            ['state_id' => $states['Bayelsa'], 'name' => 'Sagbama'],
            ['state_id' => $states['Bayelsa'], 'name' => 'Southern Ijaw'],
            ['state_id' => $states['Bayelsa'], 'name' => 'Yenagoa'],

            // Benue State
            ['state_id' => $states['Benue'], 'name' => 'Ado'],
            ['state_id' => $states['Benue'], 'name' => 'Agatu'],
            ['state_id' => $states['Benue'], 'name' => 'Apa'],
            ['state_id' => $states['Benue'], 'name' => 'Buruku'],
            ['state_id' => $states['Benue'], 'name' => 'Gboko'],
            ['state_id' => $states['Benue'], 'name' => 'Guma'],
            ['state_id' => $states['Benue'], 'name' => 'Gwer East'],
            ['state_id' => $states['Benue'], 'name' => 'Gwer West'],
            ['state_id' => $states['Benue'], 'name' => 'Katsina-Ala'],
            ['state_id' => $states['Benue'], 'name' => 'Konshisha'],
            ['state_id' => $states['Benue'], 'name' => 'Kwande'],
            ['state_id' => $states['Benue'], 'name' => 'Logo'],
            ['state_id' => $states['Benue'], 'name' => 'Makurdi'],
            ['state_id' => $states['Benue'], 'name' => 'Obi'],
            ['state_id' => $states['Benue'], 'name' => 'Ogbadibo'],
            ['state_id' => $states['Benue'], 'name' => 'Ohimini'],
            ['state_id' => $states['Benue'], 'name' => 'Oju'],
            ['state_id' => $states['Benue'], 'name' => 'Okpokwu'],
            ['state_id' => $states['Benue'], 'name' => 'Otukpo'],
            ['state_id' => $states['Benue'], 'name' => 'Tarka'],
            ['state_id' => $states['Benue'], 'name' => 'Ukum'],
            ['state_id' => $states['Benue'], 'name' => 'Ushongo'],
            ['state_id' => $states['Benue'], 'name' => 'Vandeikya'],

            // Borno State
            ['state_id' => $states['Borno'], 'name' => 'Abadam'],
            ['state_id' => $states['Borno'], 'name' => 'Askira/Uba'],
            ['state_id' => $states['Borno'], 'name' => 'Bama'],
            ['state_id' => $states['Borno'], 'name' => 'Bayo'],
            ['state_id' => $states['Borno'], 'name' => 'Biu'],
            ['state_id' => $states['Borno'], 'name' => 'Chibok'],
            ['state_id' => $states['Borno'], 'name' => 'Damboa'],
            ['state_id' => $states['Borno'], 'name' => 'Dikwa'],
            ['state_id' => $states['Borno'], 'name' => 'Gubio'],
            ['state_id' => $states['Borno'], 'name' => 'Guzamala'],
            ['state_id' => $states['Borno'], 'name' => 'Gwoza'],
            ['state_id' => $states['Borno'], 'name' => 'Hawul'],
            ['state_id' => $states['Borno'], 'name' => 'Jere'],
            ['state_id' => $states['Borno'], 'name' => 'Kaga'],
            ['state_id' => $states['Borno'], 'name' => 'Kala/Balge'],
            ['state_id' => $states['Borno'], 'name' => 'Konduga'],
            ['state_id' => $states['Borno'], 'name' => 'Kukawa'],
            ['state_id' => $states['Borno'], 'name' => 'Kwaya Kusar'],
            ['state_id' => $states['Borno'], 'name' => 'Mafa'],
            ['state_id' => $states['Borno'], 'name' => 'Magumeri'],
            ['state_id' => $states['Borno'], 'name' => 'Maiduguri'],
            ['state_id' => $states['Borno'], 'name' => 'Marte'],
            ['state_id' => $states['Borno'], 'name' => 'Mobbar'],
            ['state_id' => $states['Borno'], 'name' => 'Monguno'],
            ['state_id' => $states['Borno'], 'name' => 'Ngala'],
            ['state_id' => $states['Borno'], 'name' => 'Nganzai'],
            ['state_id' => $states['Borno'], 'name' => 'Shani'],

            // Cross River State
            ['state_id' => $states['Cross River'], 'name' => 'Abi'],
            ['state_id' => $states['Cross River'], 'name' => 'Akamkpa'],
            ['state_id' => $states['Cross River'], 'name' => 'Akpabuyo'],
            ['state_id' => $states['Cross River'], 'name' => 'Bakassi'],
            ['state_id' => $states['Cross River'], 'name' => 'Bekwarra'],
            ['state_id' => $states['Cross River'], 'name' => 'Biase'],
            ['state_id' => $states['Cross River'], 'name' => 'Boki'],
            ['state_id' => $states['Cross River'], 'name' => 'Calabar Municipal'],
            ['state_id' => $states['Cross River'], 'name' => 'Calabar South'],
            ['state_id' => $states['Cross River'], 'name' => 'Etung'],
            ['state_id' => $states['Cross River'], 'name' => 'Ikom'],
            ['state_id' => $states['Cross River'], 'name' => 'Obanliku'],
            ['state_id' => $states['Cross River'], 'name' => 'Obubra'],
            ['state_id' => $states['Cross River'], 'name' => 'Obudu'],
            ['state_id' => $states['Cross River'], 'name' => 'Odukpani'],
            ['state_id' => $states['Cross River'], 'name' => 'Ogoja'],
            ['state_id' => $states['Cross River'], 'name' => 'Yakurr'],
            ['state_id' => $states['Cross River'], 'name' => 'Yala'],

            // Delta State
            ['state_id' => $states['Delta'], 'name' => 'Aniocha North'],
            ['state_id' => $states['Delta'], 'name' => 'Aniocha South'],
            ['state_id' => $states['Delta'], 'name' => 'Bomadi'],
            ['state_id' => $states['Delta'], 'name' => 'Burutu'],
            ['state_id' => $states['Delta'], 'name' => 'Ethiope East'],
            ['state_id' => $states['Delta'], 'name' => 'Ethiope West'],
            ['state_id' => $states['Delta'], 'name' => 'Ika North East'],
            ['state_id' => $states['Delta'], 'name' => 'Ika South'],
            ['state_id' => $states['Delta'], 'name' => 'Isoko North'],
            ['state_id' => $states['Delta'], 'name' => 'Isoko South'],
            ['state_id' => $states['Delta'], 'name' => 'Ndokwa East'],
            ['state_id' => $states['Delta'], 'name' => 'Ndokwa West'],
            ['state_id' => $states['Delta'], 'name' => 'Okpe'],
            ['state_id' => $states['Delta'], 'name' => 'Oshimili North'],
            ['state_id' => $states['Delta'], 'name' => 'Oshimili South'],
            ['state_id' => $states['Delta'], 'name' => 'Patani'],
            ['state_id' => $states['Delta'], 'name' => 'Sapele'],
            ['state_id' => $states['Delta'], 'name' => 'Udu'],
            ['state_id' => $states['Delta'], 'name' => 'Ughelli North'],
            ['state_id' => $states['Delta'], 'name' => 'Ughelli South'],
            ['state_id' => $states['Delta'], 'name' => 'Ukwuani'],
            ['state_id' => $states['Delta'], 'name' => 'Uvwie'],
            ['state_id' => $states['Delta'], 'name' => 'Warri North'],
            ['state_id' => $states['Delta'], 'name' => 'Warri South'],
            ['state_id' => $states['Delta'], 'name' => 'Warri South West'],

            // Ebonyi State
            ['state_id' => $states['Ebonyi'], 'name' => 'Abakaliki'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Afikpo North'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Afikpo South'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Ebonyi'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Ezza North'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Ezza South'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Ikwo'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Ishielu'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Ivo'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Izzi'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Ohaukwu'],
            ['state_id' => $states['Ebonyi'], 'name' => 'Onicha'],

            // Edo State
            ['state_id' => $states['Edo'], 'name' => 'Akoko-Edo'],
            ['state_id' => $states['Edo'], 'name' => 'Egor'],
            ['state_id' => $states['Edo'], 'name' => 'Esan Central'],
            ['state_id' => $states['Edo'], 'name' => 'Esan North-East'],
            ['state_id' => $states['Edo'], 'name' => 'Esan South-East'],
            ['state_id' => $states['Edo'], 'name' => 'Esan West'],
            ['state_id' => $states['Edo'], 'name' => 'Etsako Central'],
            ['state_id' => $states['Edo'], 'name' => 'Etsako East'],
            ['state_id' => $states['Edo'], 'name' => 'Etsako West'],
            ['state_id' => $states['Edo'], 'name' => 'Igueben'],
            ['state_id' => $states['Edo'], 'name' => 'Ikpoba Okha'],
            ['state_id' => $states['Edo'], 'name' => 'Oredo'],
            ['state_id' => $states['Edo'], 'name' => 'Orhionmwon'],
            ['state_id' => $states['Edo'], 'name' => 'Ovia North-East'],
            ['state_id' => $states['Edo'], 'name' => 'Ovia South-West'],
            ['state_id' => $states['Edo'], 'name' => 'Owan East'],
            ['state_id' => $states['Edo'], 'name' => 'Owan West'],
            ['state_id' => $states['Edo'], 'name' => 'Uhunmwonde'],

            // Ekiti State
            ['state_id' => $states['Ekiti'], 'name' => 'Ado Ekiti'],
            ['state_id' => $states['Ekiti'], 'name' => 'Efon'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ekiti East'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ekiti South-West'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ekiti West'],
            ['state_id' => $states['Ekiti'], 'name' => 'Emure'],
            ['state_id' => $states['Ekiti'], 'name' => 'Gbonyin'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ido Osi'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ijero'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ikere'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ikole'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ilejemeje'],
            ['state_id' => $states['Ekiti'], 'name' => 'Irepodun/Ifelodun'],
            ['state_id' => $states['Ekiti'], 'name' => 'Ise/Orun'],
            ['state_id' => $states['Ekiti'], 'name' => 'Moba'],
            ['state_id' => $states['Ekiti'], 'name' => 'Oye'],

            // Enugu State
            ['state_id' => $states['Enugu'], 'name' => 'Aninri'],
            ['state_id' => $states['Enugu'], 'name' => 'Awgu'],
            ['state_id' => $states['Enugu'], 'name' => 'Enugu East'],
            ['state_id' => $states['Enugu'], 'name' => 'Enugu North'],
            ['state_id' => $states['Enugu'], 'name' => 'Enugu South'],
            ['state_id' => $states['Enugu'], 'name' => 'Ezeagu'],
            ['state_id' => $states['Enugu'], 'name' => 'Igbo Etiti'],
            ['state_id' => $states['Enugu'], 'name' => 'Igbo Eze North'],
            ['state_id' => $states['Enugu'], 'name' => 'Igbo Eze South'],
            ['state_id' => $states['Enugu'], 'name' => 'Isi Uzo'],
            ['state_id' => $states['Enugu'], 'name' => 'Nkanu East'],
            ['state_id' => $states['Enugu'], 'name' => 'Nkanu West'],
            ['state_id' => $states['Enugu'], 'name' => 'Nsukka'],
            ['state_id' => $states['Enugu'], 'name' => 'Oji River'],
            ['state_id' => $states['Enugu'], 'name' => 'Udenu'],
            ['state_id' => $states['Enugu'], 'name' => 'Udi'],
            ['state_id' => $states['Enugu'], 'name' => 'Uzo Uwani'],

            // Gombe State
            ['state_id' => $states['Gombe'], 'name' => 'Akko'],
            ['state_id' => $states['Gombe'], 'name' => 'Balanga'],
            ['state_id' => $states['Gombe'], 'name' => 'Billiri'],
            ['state_id' => $states['Gombe'], 'name' => 'Dukku'],
            ['state_id' => $states['Gombe'], 'name' => 'Funakaye'],
            ['state_id' => $states['Gombe'], 'name' => 'Gombe'],
            ['state_id' => $states['Gombe'], 'name' => 'Kaltungo'],
            ['state_id' => $states['Gombe'], 'name' => 'Kwami'],
            ['state_id' => $states['Gombe'], 'name' => 'Nafada'],
            ['state_id' => $states['Gombe'], 'name' => 'Shongom'],
            ['state_id' => $states['Gombe'], 'name' => 'Yamaltu/Deba'],

            // Imo State
            ['state_id' => $states['Imo'], 'name' => 'Aboh Mbaise'],
            ['state_id' => $states['Imo'], 'name' => 'Ahiazu Mbaise'],
            ['state_id' => $states['Imo'], 'name' => 'Ehime Mbano'],
            ['state_id' => $states['Imo'], 'name' => 'Ezinihitte'],
            ['state_id' => $states['Imo'], 'name' => 'Ideato North'],
            ['state_id' => $states['Imo'], 'name' => 'Ideato South'],
            ['state_id' => $states['Imo'], 'name' => 'Ihitte/Uboma'],
            ['state_id' => $states['Imo'], 'name' => 'Ikeduru'],
            ['state_id' => $states['Imo'], 'name' => 'Isiala Mbano'],
            ['state_id' => $states['Imo'], 'name' => 'Isu'],
            ['state_id' => $states['Imo'], 'name' => 'Mbaitoli'],
            ['state_id' => $states['Imo'], 'name' => 'Ngor Okpala'],
            ['state_id' => $states['Imo'], 'name' => 'Njaba'],
            ['state_id' => $states['Imo'], 'name' => 'Nkwerre'],
            ['state_id' => $states['Imo'], 'name' => 'Nwangele'],
            ['state_id' => $states['Imo'], 'name' => 'Obowo'],
            ['state_id' => $states['Imo'], 'name' => 'Oguta'],
            ['state_id' => $states['Imo'], 'name' => 'Ohaji/Egbema'],
            ['state_id' => $states['Imo'], 'name' => 'Okigwe'],
            ['state_id' => $states['Imo'], 'name' => 'Orlu'],
            ['state_id' => $states['Imo'], 'name' => 'Orsu'],
            ['state_id' => $states['Imo'], 'name' => 'Oru East'],
            ['state_id' => $states['Imo'], 'name' => 'Oru West'],
            ['state_id' => $states['Imo'], 'name' => 'Owerri Municipal'],
            ['state_id' => $states['Imo'], 'name' => 'Owerri North'],
            ['state_id' => $states['Imo'], 'name' => 'Owerri West'],
            ['state_id' => $states['Imo'], 'name' => 'Unuimo'],

            // Jigawa State
            ['state_id' => $states['Jigawa'], 'name' => 'Auyo'],
            ['state_id' => $states['Jigawa'], 'name' => 'Babura'],
            ['state_id' => $states['Jigawa'], 'name' => 'Biriniwa'],
            ['state_id' => $states['Jigawa'], 'name' => 'Birnin Kudu'],
            ['state_id' => $states['Jigawa'], 'name' => 'Buji'],
            ['state_id' => $states['Jigawa'], 'name' => 'Dutse'],
            ['state_id' => $states['Jigawa'], 'name' => 'Gagarawa'],
            ['state_id' => $states['Jigawa'], 'name' => 'Garki'],
            ['state_id' => $states['Jigawa'], 'name' => 'Gumel'],
            ['state_id' => $states['Jigawa'], 'name' => 'Guri'],
            ['state_id' => $states['Jigawa'], 'name' => 'Gwaram'],
            ['state_id' => $states['Jigawa'], 'name' => 'Gwiwa'],
            ['state_id' => $states['Jigawa'], 'name' => 'Hadejia'],
            ['state_id' => $states['Jigawa'], 'name' => 'Jahun'],
            ['state_id' => $states['Jigawa'], 'name' => 'Kafin Hausa'],
            ['state_id' => $states['Jigawa'], 'name' => 'Kaugama'],
            ['state_id' => $states['Jigawa'], 'name' => 'Kazaure'],
            ['state_id' => $states['Jigawa'], 'name' => 'Kiri Kasama'],
            ['state_id' => $states['Jigawa'], 'name' => 'Kiyawa'],
            ['state_id' => $states['Jigawa'], 'name' => 'Maigatari'],
            ['state_id' => $states['Jigawa'], 'name' => 'Malam Madori'],
            ['state_id' => $states['Jigawa'], 'name' => 'Miga'],
            ['state_id' => $states['Jigawa'], 'name' => 'Ringim'],
            ['state_id' => $states['Jigawa'], 'name' => 'Roni'],
            ['state_id' => $states['Jigawa'], 'name' => 'Sule Tankarkar'],
            ['state_id' => $states['Jigawa'], 'name' => 'Taura'],
            ['state_id' => $states['Jigawa'], 'name' => 'Yankwashi'],

            // Kaduna State
            ['state_id' => $states['Kaduna'], 'name' => 'Birnin Gwari'],
            ['state_id' => $states['Kaduna'], 'name' => 'Chikun'],
            ['state_id' => $states['Kaduna'], 'name' => 'Giwa'],
            ['state_id' => $states['Kaduna'], 'name' => 'Igabi'],
            ['state_id' => $states['Kaduna'], 'name' => 'Ikara'],
            ['state_id' => $states['Kaduna'], 'name' => 'Jaba'],
            ['state_id' => $states['Kaduna'], 'name' => 'Jema\'a'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kachia'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kaduna North'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kaduna South'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kagarko'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kajuru'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kaura'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kauru'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kubau'],
            ['state_id' => $states['Kaduna'], 'name' => 'Kudan'],
            ['state_id' => $states['Kaduna'], 'name' => 'Lere'],
            ['state_id' => $states['Kaduna'], 'name' => 'Makarfi'],
            ['state_id' => $states['Kaduna'], 'name' => 'Sabon Gari'],
            ['state_id' => $states['Kaduna'], 'name' => 'Sanga'],
            ['state_id' => $states['Kaduna'], 'name' => 'Soba'],
            ['state_id' => $states['Kaduna'], 'name' => 'Zangon Kataf'],
            ['state_id' => $states['Kaduna'], 'name' => 'Zaria'],

            // Kano State
            ['state_id' => $states['Kano'], 'name' => 'Ajingi'],
            ['state_id' => $states['Kano'], 'name' => 'Albasu'],
            ['state_id' => $states['Kano'], 'name' => 'Bagwai'],
            ['state_id' => $states['Kano'], 'name' => 'Bebeji'],
            ['state_id' => $states['Kano'], 'name' => 'Bichi'],
            ['state_id' => $states['Kano'], 'name' => 'Bunkure'],
            ['state_id' => $states['Kano'], 'name' => 'Dala'],
            ['state_id' => $states['Kano'], 'name' => 'Dambatta'],
            ['state_id' => $states['Kano'], 'name' => 'Dawakin Kudu'],
            ['state_id' => $states['Kano'], 'name' => 'Dawakin Tofa'],
            ['state_id' => $states['Kano'], 'name' => 'Doguwa'],
            ['state_id' => $states['Kano'], 'name' => 'Fagge'],
            ['state_id' => $states['Kano'], 'name' => 'Gabasawa'],
            ['state_id' => $states['Kano'], 'name' => 'Garko'],
            ['state_id' => $states['Kano'], 'name' => 'Garun Mallam'],
            ['state_id' => $states['Kano'], 'name' => 'Gaya'],
            ['state_id' => $states['Kano'], 'name' => 'Gezawa'],
            ['state_id' => $states['Kano'], 'name' => 'Gwale'],
            ['state_id' => $states['Kano'], 'name' => 'Gwarzo'],
            ['state_id' => $states['Kano'], 'name' => 'Kabo'],
            ['state_id' => $states['Kano'], 'name' => 'Kano Municipal'],
            ['state_id' => $states['Kano'], 'name' => 'Karaye'],
            ['state_id' => $states['Kano'], 'name' => 'Kibiya'],
            ['state_id' => $states['Kano'], 'name' => 'Kiru'],
            ['state_id' => $states['Kano'], 'name' => 'Kumbotso'],
            ['state_id' => $states['Kano'], 'name' => 'Kunchi'],
            ['state_id' => $states['Kano'], 'name' => 'Kura'],
            ['state_id' => $states['Kano'], 'name' => 'Madobi'],
            ['state_id' => $states['Kano'], 'name' => 'Makoda'],
            ['state_id' => $states['Kano'], 'name' => 'Minjibir'],
            ['state_id' => $states['Kano'], 'name' => 'Nasarawa'],
            ['state_id' => $states['Kano'], 'name' => 'Rano'],
            ['state_id' => $states['Kano'], 'name' => 'Rimin Gado'],
            ['state_id' => $states['Kano'], 'name' => 'Rogo'],
            ['state_id' => $states['Kano'], 'name' => 'Shanono'],
            ['state_id' => $states['Kano'], 'name' => 'Sumaila'],
            ['state_id' => $states['Kano'], 'name' => 'Takai'],
            ['state_id' => $states['Kano'], 'name' => 'Tarauni'],
            ['state_id' => $states['Kano'], 'name' => 'Tofa'],
            ['state_id' => $states['Kano'], 'name' => 'Tsanyawa'],
            ['state_id' => $states['Kano'], 'name' => 'Tudun Wada'],
            ['state_id' => $states['Kano'], 'name' => 'Ungogo'],
            ['state_id' => $states['Kano'], 'name' => 'Warawa'],
            ['state_id' => $states['Kano'], 'name' => 'Wudil'],

            // Katsina State
            ['state_id' => $states['Katsina'], 'name' => 'Bakori'],
            ['state_id' => $states['Katsina'], 'name' => 'Batagarawa'],
            ['state_id' => $states['Katsina'], 'name' => 'Batsari'],
            ['state_id' => $states['Katsina'], 'name' => 'Baure'],
            ['state_id' => $states['Katsina'], 'name' => 'Bindawa'],
            ['state_id' => $states['Katsina'], 'name' => 'Charanchi'],
            ['state_id' => $states['Katsina'], 'name' => 'Dan Musa'],
            ['state_id' => $states['Katsina'], 'name' => 'Dandume'],
            ['state_id' => $states['Katsina'], 'name' => 'Danja'],
            ['state_id' => $states['Katsina'], 'name' => 'Daura'],
            ['state_id' => $states['Katsina'], 'name' => 'Dutsi'],
            ['state_id' => $states['Katsina'], 'name' => 'Dutsin Ma'],
            ['state_id' => $states['Katsina'], 'name' => 'Faskari'],
            ['state_id' => $states['Katsina'], 'name' => 'Funtua'],
            ['state_id' => $states['Katsina'], 'name' => 'Ingawa'],
            ['state_id' => $states['Katsina'], 'name' => 'Jibia'],
            ['state_id' => $states['Katsina'], 'name' => 'Kafur'],
            ['state_id' => $states['Katsina'], 'name' => 'Kaita'],
            ['state_id' => $states['Katsina'], 'name' => 'Kankara'],
            ['state_id' => $states['Katsina'], 'name' => 'Kankia'],
            ['state_id' => $states['Katsina'], 'name' => 'Katsina'],
            ['state_id' => $states['Katsina'], 'name' => 'Kurfi'],
            ['state_id' => $states['Katsina'], 'name' => 'Kusada'],
            ['state_id' => $states['Katsina'], 'name' => 'Mai\'Adua'],
            ['state_id' => $states['Katsina'], 'name' => 'Malumfashi'],
            ['state_id' => $states['Katsina'], 'name' => 'Mani'],
            ['state_id' => $states['Katsina'], 'name' => 'Mashi'],
            ['state_id' => $states['Katsina'], 'name' => 'Matazu'],
            ['state_id' => $states['Katsina'], 'name' => 'Musawa'],
            ['state_id' => $states['Katsina'], 'name' => 'Rimi'],
            ['state_id' => $states['Katsina'], 'name' => 'Sabuwa'],
            ['state_id' => $states['Katsina'], 'name' => 'Safana'],
            ['state_id' => $states['Katsina'], 'name' => 'Sandamu'],
            ['state_id' => $states['Katsina'], 'name' => 'Zango'],

            // Kebbi State
            ['state_id' => $states['Kebbi'], 'name' => 'Aleiro'],
            ['state_id' => $states['Kebbi'], 'name' => 'Arewa Dandi'],
            ['state_id' => $states['Kebbi'], 'name' => 'Argungu'],
            ['state_id' => $states['Kebbi'], 'name' => 'Augie'],
            ['state_id' => $states['Kebbi'], 'name' => 'Bagudo'],
            ['state_id' => $states['Kebbi'], 'name' => 'Birnin Kebbi'],
            ['state_id' => $states['Kebbi'], 'name' => 'Bunza'],
            ['state_id' => $states['Kebbi'], 'name' => 'Dandi'],
            ['state_id' => $states['Kebbi'], 'name' => 'Fakai'],
            ['state_id' => $states['Kebbi'], 'name' => 'Gwandu'],
            ['state_id' => $states['Kebbi'], 'name' => 'Jega'],
            ['state_id' => $states['Kebbi'], 'name' => 'Kalgo'],
            ['state_id' => $states['Kebbi'], 'name' => 'Koko/Besse'],
            ['state_id' => $states['Kebbi'], 'name' => 'Maiyama'],
            ['state_id' => $states['Kebbi'], 'name' => 'Ngaski'],
            ['state_id' => $states['Kebbi'], 'name' => 'Sakaba'],
            ['state_id' => $states['Kebbi'], 'name' => 'Shanga'],
            ['state_id' => $states['Kebbi'], 'name' => 'Suru'],
            ['state_id' => $states['Kebbi'], 'name' => 'Danko/Wasagu'],
            ['state_id' => $states['Kebbi'], 'name' => 'Yauri'],
            ['state_id' => $states['Kebbi'], 'name' => 'Zuru'],

            // Kogi State
            ['state_id' => $states['Kogi'], 'name' => 'Adavi'],
            ['state_id' => $states['Kogi'], 'name' => 'Ajaokuta'],
            ['state_id' => $states['Kogi'], 'name' => 'Ankpa'],
            ['state_id' => $states['Kogi'], 'name' => 'Bassa'],
            ['state_id' => $states['Kogi'], 'name' => 'Dekina'],
            ['state_id' => $states['Kogi'], 'name' => 'Ibaji'],
            ['state_id' => $states['Kogi'], 'name' => 'Idah'],
            ['state_id' => $states['Kogi'], 'name' => 'Igalamela-Odolu'],
            ['state_id' => $states['Kogi'], 'name' => 'Ijumu'],
            ['state_id' => $states['Kogi'], 'name' => 'Kabba/Bunu'],
            ['state_id' => $states['Kogi'], 'name' => 'Kogi'],
            ['state_id' => $states['Kogi'], 'name' => 'Lokoja'],
            ['state_id' => $states['Kogi'], 'name' => 'Mopa-Muro'],
            ['state_id' => $states['Kogi'], 'name' => 'Ofu'],
            ['state_id' => $states['Kogi'], 'name' => 'Ogori/Magongo'],
            ['state_id' => $states['Kogi'], 'name' => 'Okehi'],
            ['state_id' => $states['Kogi'], 'name' => 'Okene'],
            ['state_id' => $states['Kogi'], 'name' => 'Olamaboro'],
            ['state_id' => $states['Kogi'], 'name' => 'Omala'],
            ['state_id' => $states['Kogi'], 'name' => 'Yagba East'],
            ['state_id' => $states['Kogi'], 'name' => 'Yagba West'],

            // Kwara State
            ['state_id' => $states['Kwara'], 'name' => 'Asa'],
            ['state_id' => $states['Kwara'], 'name' => 'Baruten'],
            ['state_id' => $states['Kwara'], 'name' => 'Edu'],
            ['state_id' => $states['Kwara'], 'name' => 'Ekiti'],
            ['state_id' => $states['Kwara'], 'name' => 'Ifelodun'],
            ['state_id' => $states['Kwara'], 'name' => 'Ilorin East'],
            ['state_id' => $states['Kwara'], 'name' => 'Ilorin South'],
            ['state_id' => $states['Kwara'], 'name' => 'Ilorin West'],
            ['state_id' => $states['Kwara'], 'name' => 'Irepodun'],
            ['state_id' => $states['Kwara'], 'name' => 'Isin'],
            ['state_id' => $states['Kwara'], 'name' => 'Kaiama'],
            ['state_id' => $states['Kwara'], 'name' => 'Moro'],
            ['state_id' => $states['Kwara'], 'name' => 'Offa'],
            ['state_id' => $states['Kwara'], 'name' => 'Oke Ero'],
            ['state_id' => $states['Kwara'], 'name' => 'Oyun'],
            ['state_id' => $states['Kwara'], 'name' => 'Pategi'],

            // Lagos State
            ['state_id' => $states['Lagos'], 'name' => 'Agege'],
            ['state_id' => $states['Lagos'], 'name' => 'Ajeromi-Ifelodun'],
            ['state_id' => $states['Lagos'], 'name' => 'Alimosho'],
            ['state_id' => $states['Lagos'], 'name' => 'Amuwo-Odofin'],
            ['state_id' => $states['Lagos'], 'name' => 'Apapa'],
            ['state_id' => $states['Lagos'], 'name' => 'Badagry'],
            ['state_id' => $states['Lagos'], 'name' => 'Epe'],
            ['state_id' => $states['Lagos'], 'name' => 'Eti Osa'],
            ['state_id' => $states['Lagos'], 'name' => 'Ibeju-Lekki'],
            ['state_id' => $states['Lagos'], 'name' => 'Ifako-Ijaiye'],
            ['state_id' => $states['Lagos'], 'name' => 'Ikeja'],
            ['state_id' => $states['Lagos'], 'name' => 'Ikorodu'],
            ['state_id' => $states['Lagos'], 'name' => 'Kosofe'],
            ['state_id' => $states['Lagos'], 'name' => 'Lagos Island'],
            ['state_id' => $states['Lagos'], 'name' => 'Lagos Mainland'],
            ['state_id' => $states['Lagos'], 'name' => 'Mushin'],
            ['state_id' => $states['Lagos'], 'name' => 'Ojo'],
            ['state_id' => $states['Lagos'], 'name' => 'Oshodi-Isolo'],
            ['state_id' => $states['Lagos'], 'name' => 'Shomolu'],
            ['state_id' => $states['Lagos'], 'name' => 'Surulere'],

            // Nasarawa State
            ['state_id' => $states['Nasarawa'], 'name' => 'Akwanga'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Awe'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Doma'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Karu'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Keana'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Keffi'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Kokona'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Lafia'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Nasarawa'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Nasarawa Egon'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Obi'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Toto'],
            ['state_id' => $states['Nasarawa'], 'name' => 'Wamba'],

            // Niger State
            ['state_id' => $states['Niger'], 'name' => 'Agaie'],
            ['state_id' => $states['Niger'], 'name' => 'Agwara'],
            ['state_id' => $states['Niger'], 'name' => 'Bida'],
            ['state_id' => $states['Niger'], 'name' => 'Borgu'],
            ['state_id' => $states['Niger'], 'name' => 'Bosso'],
            ['state_id' => $states['Niger'], 'name' => 'Chanchaga'],
            ['state_id' => $states['Niger'], 'name' => 'Edati'],
            ['state_id' => $states['Niger'], 'name' => 'Gbako'],
            ['state_id' => $states['Niger'], 'name' => 'Gurara'],
            ['state_id' => $states['Niger'], 'name' => 'Katcha'],
            ['state_id' => $states['Niger'], 'name' => 'Kontagora'],
            ['state_id' => $states['Niger'], 'name' => 'Lapai'],
            ['state_id' => $states['Niger'], 'name' => 'Lavun'],
            ['state_id' => $states['Niger'], 'name' => 'Magama'],
            ['state_id' => $states['Niger'], 'name' => 'Mariga'],
            ['state_id' => $states['Niger'], 'name' => 'Mashegu'],
            ['state_id' => $states['Niger'], 'name' => 'Mokwa'],
            ['state_id' => $states['Niger'], 'name' => 'Muya'],
            ['state_id' => $states['Niger'], 'name' => 'Paikoro'],
            ['state_id' => $states['Niger'], 'name' => 'Rafi'],
            ['state_id' => $states['Niger'], 'name' => 'Rijau'],
            ['state_id' => $states['Niger'], 'name' => 'Shiroro'],
            ['state_id' => $states['Niger'], 'name' => 'Suleja'],
            ['state_id' => $states['Niger'], 'name' => 'Tafa'],
            ['state_id' => $states['Niger'], 'name' => 'Wushishi'],

            // Ogun State
            ['state_id' => $states['Ogun'], 'name' => 'Abeokuta North'],
            ['state_id' => $states['Ogun'], 'name' => 'Abeokuta South'],
            ['state_id' => $states['Ogun'], 'name' => 'Ado-Odo/Ota'],
            ['state_id' => $states['Ogun'], 'name' => 'Ewekoro'],
            ['state_id' => $states['Ogun'], 'name' => 'Ifo'],
            ['state_id' => $states['Ogun'], 'name' => 'Ijebu East'],
            ['state_id' => $states['Ogun'], 'name' => 'Ijebu North'],
            ['state_id' => $states['Ogun'], 'name' => 'Ijebu North East'],
            ['state_id' => $states['Ogun'], 'name' => 'Ijebu Ode'],
            ['state_id' => $states['Ogun'], 'name' => 'Ikenne'],
            ['state_id' => $states['Ogun'], 'name' => 'Imeko Afon'],
            ['state_id' => $states['Ogun'], 'name' => 'Ipokia'],
            ['state_id' => $states['Ogun'], 'name' => 'Obafemi Owode'],
            ['state_id' => $states['Ogun'], 'name' => 'Ogun Waterside'],
            ['state_id' => $states['Ogun'], 'name' => 'Odeda'],
            ['state_id' => $states['Ogun'], 'name' => 'Odogbolu'],
            ['state_id' => $states['Ogun'], 'name' => 'Remo North'],
            ['state_id' => $states['Ogun'], 'name' => 'Shagamu'],
            ['state_id' => $states['Ogun'], 'name' => 'Yewa North'],
            ['state_id' => $states['Ogun'], 'name' => 'Yewa South'],

            // Ondo State
            ['state_id' => $states['Ondo'], 'name' => 'Akoko North-East'],
            ['state_id' => $states['Ondo'], 'name' => 'Akoko North-West'],
            ['state_id' => $states['Ondo'], 'name' => 'Akoko South-East'],
            ['state_id' => $states['Ondo'], 'name' => 'Akoko South-West'],
            ['state_id' => $states['Ondo'], 'name' => 'Akure North'],
            ['state_id' => $states['Ondo'], 'name' => 'Akure South'],
            ['state_id' => $states['Ondo'], 'name' => 'Ese Odo'],
            ['state_id' => $states['Ondo'], 'name' => 'Idanre'],
            ['state_id' => $states['Ondo'], 'name' => 'Ifedore'],
            ['state_id' => $states['Ondo'], 'name' => 'Ilaje'],
            ['state_id' => $states['Ondo'], 'name' => 'Ile Oluji/Okeigbo'],
            ['state_id' => $states['Ondo'], 'name' => 'Irele'],
            ['state_id' => $states['Ondo'], 'name' => 'Odigbo'],
            ['state_id' => $states['Ondo'], 'name' => 'Okitipupa'],
            ['state_id' => $states['Ondo'], 'name' => 'Ondo East'],
            ['state_id' => $states['Ondo'], 'name' => 'Ondo West'],
            ['state_id' => $states['Ondo'], 'name' => 'Ose'],
            ['state_id' => $states['Ondo'], 'name' => 'Owo'],

            // Osun State
            ['state_id' => $states['Osun'], 'name' => 'Aiyedaade'],
            ['state_id' => $states['Osun'], 'name' => 'Aiyedire'],
            ['state_id' => $states['Osun'], 'name' => 'Atakunmosa East'],
            ['state_id' => $states['Osun'], 'name' => 'Atakunmosa West'],
            ['state_id' => $states['Osun'], 'name' => 'Boluwaduro'],
            ['state_id' => $states['Osun'], 'name' => 'Boripe'],
            ['state_id' => $states['Osun'], 'name' => 'Ede North'],
            ['state_id' => $states['Osun'], 'name' => 'Ede South'],
            ['state_id' => $states['Osun'], 'name' => 'Egbedore'],
            ['state_id' => $states['Osun'], 'name' => 'Ejigbo'],
            ['state_id' => $states['Osun'], 'name' => 'Ife Central'],
            ['state_id' => $states['Osun'], 'name' => 'Ife East'],
            ['state_id' => $states['Osun'], 'name' => 'Ife North'],
            ['state_id' => $states['Osun'], 'name' => 'Ife South'],
            ['state_id' => $states['Osun'], 'name' => 'Ifedayo'],
            ['state_id' => $states['Osun'], 'name' => 'Ifelodun'],
            ['state_id' => $states['Osun'], 'name' => 'Ila'],
            ['state_id' => $states['Osun'], 'name' => 'Ilesa East'],
            ['state_id' => $states['Osun'], 'name' => 'Ilesa West'],
            ['state_id' => $states['Osun'], 'name' => 'Irepodun'],
            ['state_id' => $states['Osun'], 'name' => 'Irewole'],
            ['state_id' => $states['Osun'], 'name' => 'Isokan'],
            ['state_id' => $states['Osun'], 'name' => 'Iwo'],
            ['state_id' => $states['Osun'], 'name' => 'Obokun'],
            ['state_id' => $states['Osun'], 'name' => 'Odo Otin'],
            ['state_id' => $states['Osun'], 'name' => 'Ola Oluwa'],
            ['state_id' => $states['Osun'], 'name' => 'Olorunda'],
            ['state_id' => $states['Osun'], 'name' => 'Oriade'],
            ['state_id' => $states['Osun'], 'name' => 'Orolu'],
            ['state_id' => $states['Osun'], 'name' => 'Osogbo'],
            //  OYO
            ['state_id' => $states['Oyo'], 'name' => 'Afijio'],
            ['state_id' => $states['Oyo'], 'name' => 'Akinyele'],
            ['state_id' => $states['Oyo'], 'name' => 'Atiba'],
            ['state_id' => $states['Oyo'], 'name' => 'Atisbo'],
            ['state_id' => $states['Oyo'], 'name' => 'Egbeda'],
            ['state_id' => $states['Oyo'], 'name' => 'Ibadan North'],
            ['state_id' => $states['Oyo'], 'name' => 'Ibadan North-East'],
            ['state_id' => $states['Oyo'], 'name' => 'Ibadan North-West'],
            ['state_id' => $states['Oyo'], 'name' => 'Ibadan South-East'],
            ['state_id' => $states['Oyo'], 'name' => 'Ibadan South-West'],
            ['state_id' => $states['Oyo'], 'name' => 'Ibarapa Central'],
            ['state_id' => $states['Oyo'], 'name' => 'Ibarapa East'],
            ['state_id' => $states['Oyo'], 'name' => 'Ibarapa North'],
            ['state_id' => $states['Oyo'], 'name' => 'Ido'],
            ['state_id' => $states['Oyo'], 'name' => 'Irepo'],
            ['state_id' => $states['Oyo'], 'name' => 'Iseyin'],
            ['state_id' => $states['Oyo'], 'name' => 'Itesiwaju'],
            ['state_id' => $states['Oyo'], 'name' => 'Lagelu'],
            ['state_id' => $states['Oyo'], 'name' => 'Ogbomosho North'],
            ['state_id' => $states['Oyo'], 'name' => 'Ogbomosho South'],
            ['state_id' => $states['Oyo'], 'name' => 'Oyo East'],
            ['state_id' => $states['Oyo'], 'name' => 'Oyo West'],
            ['state_id' => $states['Oyo'], 'name' => 'Saki East'],
            ['state_id' => $states['Oyo'], 'name' => 'Saki West'],
            ['state_id' => $states['Oyo'], 'name' => 'Surulere'],

            // Plateau State
            ['state_id' => $states['Plateau'], 'name' => 'Barkin Ladi'],
            ['state_id' => $states['Plateau'], 'name' => 'Bassa'],
            ['state_id' => $states['Plateau'], 'name' => 'Battal'],
            ['state_id' => $states['Plateau'], 'name' => 'Bokkos'],
            ['state_id' => $states['Plateau'], 'name' => 'Jos East'],
            ['state_id' => $states['Plateau'], 'name' => 'Jos North'],
            ['state_id' => $states['Plateau'], 'name' => 'Jos South'],
            ['state_id' => $states['Plateau'], 'name' => 'Kanam'],
            ['state_id' => $states['Plateau'], 'name' => 'Kanke'],
            ['state_id' => $states['Plateau'], 'name' => 'Langtang North'],
            ['state_id' => $states['Plateau'], 'name' => 'Langtang South'],
            ['state_id' => $states['Plateau'], 'name' => 'Mangu'],
            ['state_id' => $states['Plateau'], 'name' => 'Pankshin'],
            ['state_id' => $states['Plateau'], 'name' => 'Riyom'],
            ['state_id' => $states['Plateau'], 'name' => 'Shendam'],
            ['state_id' => $states['Plateau'], 'name' => 'Wase'],

            // Rivers State
            ['state_id' => $states['Rivers'], 'name' => 'Abua/Odual'],
            ['state_id' => $states['Rivers'], 'name' => 'Ahoada East'],
            ['state_id' => $states['Rivers'], 'name' => 'Ahoada West'],
            ['state_id' => $states['Rivers'], 'name' => 'Akuku-Toru'],
            ['state_id' => $states['Rivers'], 'name' => 'Andoni'],
            ['state_id' => $states['Rivers'], 'name' => 'Asari-Toru'],
            ['state_id' => $states['Rivers'], 'name' => 'Bonny'],
            ['state_id' => $states['Rivers'], 'name' => 'Degema'],
            ['state_id' => $states['Rivers'], 'name' => 'Emohua'],
            ['state_id' => $states['Rivers'], 'name' => 'Ikwerre'],
            ['state_id' => $states['Rivers'], 'name' => 'Khana'],
            ['state_id' => $states['Rivers'], 'name' => 'Obio/Akpor'],
            ['state_id' => $states['Rivers'], 'name' => 'Ogba/Egbema/Ndoni'],
            ['state_id' => $states['Rivers'], 'name' => 'Ogu/Bolo'],
            ['state_id' => $states['Rivers'], 'name' => 'Okrika'],
            ['state_id' => $states['Rivers'], 'name' => 'Omuma'],
            ['state_id' => $states['Rivers'], 'name' => 'Opobo/Nkoro'],
            ['state_id' => $states['Rivers'], 'name' => 'Port Harcourt'],
            ['state_id' => $states['Rivers'], 'name' => 'Tai'],

            // Sokoto State
            ['state_id' => $states['Sokoto'], 'name' => 'Binji'],
            ['state_id' => $states['Sokoto'], 'name' => 'Bodinga'],
            ['state_id' => $states['Sokoto'], 'name' => 'Dange/Shuni'],
            ['state_id' => $states['Sokoto'], 'name' => 'Gada'],
            ['state_id' => $states['Sokoto'], 'name' => 'Goronyo'],
            ['state_id' => $states['Sokoto'], 'name' => 'Gudu'],
            ['state_id' => $states['Sokoto'], 'name' => 'Illela'],
            ['state_id' => $states['Sokoto'], 'name' => 'Kebbe'],
            ['state_id' => $states['Sokoto'], 'name' => 'Kware'],
            ['state_id' => $states['Sokoto'], 'name' => 'Rabah'],
            ['state_id' => $states['Sokoto'], 'name' => 'Sokoto North'],
            ['state_id' => $states['Sokoto'], 'name' => 'Sokoto South'],
            ['state_id' => $states['Sokoto'], 'name' => 'Tambuwal'],
            ['state_id' => $states['Sokoto'], 'name' => 'Tangaza'],
            ['state_id' => $states['Sokoto'], 'name' => 'Tureta'],
            ['state_id' => $states['Sokoto'], 'name' => 'Wamako'],
            ['state_id' => $states['Sokoto'], 'name' => 'Wurno'],
            ['state_id' => $states['Sokoto'], 'name' => 'Yabo'],

            // Taraba State
            ['state_id' => $states['Taraba'], 'name' => 'Ardo-Kola'],
            ['state_id' => $states['Taraba'], 'name' => 'Bali'],
            ['state_id' => $states['Taraba'], 'name' => 'Donga'],
            ['state_id' => $states['Taraba'], 'name' => 'Gashaka'],
            ['state_id' => $states['Taraba'], 'name' => 'Gassol'],
            ['state_id' => $states['Taraba'], 'name' => 'Ibi'],
            ['state_id' => $states['Taraba'], 'name' => 'Jalingo'],
            ['state_id' => $states['Taraba'], 'name' => 'Karim-Lamido'],
            ['state_id' => $states['Taraba'], 'name' => 'Kumi'],
            ['state_id' => $states['Taraba'], 'name' => 'Lau'],
            ['state_id' => $states['Taraba'], 'name' => 'Sardauna'],
            ['state_id' => $states['Taraba'], 'name' => 'Takum'],
            ['state_id' => $states['Taraba'], 'name' => 'Ussa'],
            ['state_id' => $states['Taraba'], 'name' => 'Wukari'],
            ['state_id' => $states['Taraba'], 'name' => 'Yorro'],
            ['state_id' => $states['Taraba'], 'name' => 'Zing'],

            // Yobe State
            ['state_id' => $states['Yobe'], 'name' => 'Bade'],
            ['state_id' => $states['Yobe'], 'name' => 'Bursari'],
            ['state_id' => $states['Yobe'], 'name' => 'Damaturu'],
            ['state_id' => $states['Yobe'], 'name' => 'Fika'],
            ['state_id' => $states['Yobe'], 'name' => 'Fune'],
            ['state_id' => $states['Yobe'], 'name' => 'Geidam'],
            ['state_id' => $states['Yobe'], 'name' => 'Gujba'],
            ['state_id' => $states['Yobe'], 'name' => 'Gulani'],
            ['state_id' => $states['Yobe'], 'name' => 'Jakusko'],
            ['state_id' => $states['Yobe'], 'name' => 'Jigawa'],
            ['state_id' => $states['Yobe'], 'name' => 'Karasuwa'],
            ['state_id' => $states['Yobe'], 'name' => 'Machina'],
            ['state_id' => $states['Yobe'], 'name' => 'Nguru'],
            ['state_id' => $states['Yobe'], 'name' => 'Potiskum'],
            ['state_id' => $states['Yobe'], 'name' => 'Tarmuwa'],
            ['state_id' => $states['Yobe'], 'name' => 'Yunusari'],
            ['state_id' => $states['Yobe'], 'name' => 'Yusufari'],

            // Zamfara State
            ['state_id' => $states['Zamfara'], 'name' => 'Anka'],
            ['state_id' => $states['Zamfara'], 'name' => 'Bakura'],
            ['state_id' => $states['Zamfara'], 'name' => 'Birnin Magaji'],
            ['state_id' => $states['Zamfara'], 'name' => 'Bukkuyum'],
            ['state_id' => $states['Zamfara'], 'name' => 'Chafe'],
            ['state_id' => $states['Zamfara'], 'name' => 'Gummi'],
            ['state_id' => $states['Zamfara'], 'name' => 'Gusau'],
            ['state_id' => $states['Zamfara'], 'name' => 'Kaura Namoda'],
            ['state_id' => $states['Zamfara'], 'name' => 'Maradun'],
            ['state_id' => $states['Zamfara'], 'name' => 'Maru'],
            ['state_id' => $states['Zamfara'], 'name' => 'Shinkafi'],
            ['state_id' => $states['Zamfara'], 'name' => 'Talata Mafara'],
            ['state_id' => $states['Zamfara'], 'name' => 'Zurmi'],

            // abuja
            ['state_id' => $states['FCT'], 'name' => 'Abaji'],
            ['state_id' => $states['FCT'], 'name' => 'Bwari'],
            ['state_id' => $states['FCT'], 'name' => 'Gwagwalada'],
            ['state_id' => $states['FCT'], 'name' => 'Kuje'],
            ['state_id' => $states['FCT'], 'name' => 'Kwali'],
            ['state_id' => $states['FCT'], 'name' => 'Municipal']  // For the Abuja Municipal Area Council (AMAC)
        ];

        // Insert the LGAs into the database
        DB::table('lgas')->insert($lgas);
    }
}
